
spring:
  datasource:
    url: jdbc:mysql://47.94.159.133:3306/fafu1?useSSL=FALSE&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
  resources:
    static-locations: file:/img/,file:/zip/,file:/wetland/,file:/water/,file:/soil/,file:/outcome/,file:/forest/,file:/balant_sheet/,file:/notice_file/
  thymeleaf:
     cache: false
  task:
    execution:
      pool:
        core-size: 20
        max-size: 40
        keep-alive: 300
        queue-capacity: 50
  jackson:
    time-zone: GMT+8

mybatis:
  type-aliases-package: com.fafu.dao
pagehelper:
  helperDialect: mysql
  reasonable: true
server:
  port: 8888
#redis:
#  host: 127.0.0.1
#  prot: 6379
#  jedis:
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0
#  timeout: 0
device:
  img.path: D:\IntelliJIDEAText\News\resources\img\
  water.path: D:\IntelliJIDEAText\News\resources\water\
  soil.path: D:\IntelliJIDEAText\News\resources\soil\
  wetland.path: D:\IntelliJIDEAText\News\resources\wetland\
  forest.path: D:\IntelliJIDEAText\News\resources\forest\
  outcome.path: D:\IntelliJIDEAText\News\resources\outcome\
  balance_sheet.path: D:\IntelliJIDEAText\News\resources\balance_sheet\
  zip.path: D:\IntelliJIDEAText\News\resources\zip\
  notice_file.path: D:\IntelliJIDEAText\News\resources\notice_file\
  standard_file.path: D:\IntelliJIDEAText\News\resources\standard_file\
  industry_standard.path: D:\IntelliJIDEAText\News\resources\industry_standard\



#  img.path: /root/reources/img/
#  water.path: /root/reources/water/
#  soil.path: /root/reources/soil/
#  wetland.path: /root/reources/wetland/
#  forest.path: /root/reources/forest/
#  outcome.path: /root/reources/outcome/
#  balance_sheet.path: /root/reources/balance_sheet/
#  zip.path: /root/reources/zip/
#  notice_file.path: /root/reources/notice_file/
#  standard_file.path: /root/reources/standard_file/
#  industry_standard.path: /root/reources/industry_standard/




#  img.path: /root/www/server/springboot/reources/img/
#  water.path: /root/www/server/springboot/reources/water/
#  soil.path: /root/www/server/springboot/reources/soil/
#  wetland.path: /root/www/server/springboot/reources/wetland/
#  forest.path: /root/www/server/springboot/reources/forest/
#  outcome.path: /root/www/server/springboot/reources/outcome/
#  balance_sheet.path: /root/www/server/springboot/reources/balance_sheet/
#  zip.path: /root/www/server/springboot/reources/zip/
#  notice_file.path: /root/www/server/springboot/reources/notice_file/
#  standard_file.path: /root/www/server/springboot/reources/standard_file/
#  industry_standard.path: /root/www/server/springboot/reources/industry_standard/
web:
  DownloadUrl: "http://localhost:80"
